remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tangel Studio官网
show_downloads: false
description: <a href="https://imgse.com/i/piNbdgS"><img src="https://s11.ax1x.com/2023/11/19/piNbdgS.png" alt="piNbdgS.png" border="0" /></a>